<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.fixtures_load_command' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Command/DoctrineCommand.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Loader.php';
include_once $this->targetDirs[3].'/vendor/symfony/doctrine-bridge/DataFixtures/ContainerAwareLoader.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/Loader/SymfonyFixturesLoader.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/FixtureInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/SharedFixtureInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/AbstractFixture.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/ORMFixtureInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php';
include_once $this->targetDirs[3].'/src/DataFixtures/AppFixtures.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Fixtures/AgentGroups.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Fixtures/AgentPrivileges.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Fixtures/EmailTemplates.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Fixtures/HelpdeskBranding.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Fixtures/TicketPriorities.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Fixtures/TicketStatuses.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Fixtures/TicketTypes.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Fixtures/UserRoles.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/automation-bundle/Fixtures/AutomationWorkflowFixtures.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/support-center-bundle/Fixtures/EmailTemplates.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/support-center-bundle/Fixtures/KnowledgebaseWebsite.php';

$a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($this);
$a->addFixtures([0 => ['fixture' => new \App\DataFixtures\AppFixtures(), 'groups' => []], 1 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\AgentGroups(), 'groups' => []], 2 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\AgentPrivileges(), 'groups' => []], 3 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\EmailTemplates(), 'groups' => []], 4 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\HelpdeskBranding(), 'groups' => []], 5 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\TicketPriorities(), 'groups' => []], 6 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\TicketStatuses(), 'groups' => []], 7 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\TicketTypes(), 'groups' => []], 8 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\UserRoles(), 'groups' => []], 9 => ['fixture' => new \Webkul\UVDesk\AutomationBundle\Fixtures\AutomationWorkflowFixtures(), 'groups' => []], 10 => ['fixture' => new \Webkul\UVDesk\SupportCenterBundle\Fixtures\EmailTemplates(), 'groups' => []], 11 => ['fixture' => new \Webkul\UVDesk\SupportCenterBundle\Fixtures\KnowledgebaseWebsite(), 'groups' => []]]);

$this->privates['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a, ($this->services['doctrine'] ?? $this->getDoctrineService()));

$instance->setName('doctrine:fixtures:load');

return $instance;
