<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Webkul\UVDesk\ExtensionFrameworkBundle\Application\Routine\RenderDashboardRoutine' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/event-dispatcher/Event.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/extension-framework/Application/RoutineInterface.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/extension-framework/Application/Routine/RenderDashboardRoutine.php';

return $this->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Application\\Routine\\RenderDashboardRoutine'] = new \Webkul\UVDesk\ExtensionFrameworkBundle\Application\Routine\RenderDashboardRoutine(($this->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Dashboard\\DashboardTemplate'] ?? $this->getDashboardTemplateService()));
