<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'swiftmailer.command.debug' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/swiftmailer-bundle/Command/AbstractSwiftMailerCommand.php';
include_once $this->targetDirs[3].'/vendor/symfony/swiftmailer-bundle/Command/DebugCommand.php';

$this->privates['swiftmailer.command.debug'] = $instance = new \Symfony\Bundle\SwiftmailerBundle\Command\DebugCommand();

$instance->setName('debug:swiftmailer');

return $instance;
