<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.aC5KO5E' shared service.

return $this->privates['.service_locator.aC5KO5E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'applicationCollection' => ['privates', 'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Utils\\ApplicationCollection', 'getApplicationCollectionService.php', true],
    'event' => ['privates', 'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Application\\Routine\\ApiRoutine', 'getApiRoutineService.php', true],
], [
    'applicationCollection' => 'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Utils\\ApplicationCollection',
    'event' => 'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Application\\Routine\\ApiRoutine',
]);
