<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.registry' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormRegistryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormRegistry.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/Extension/DependencyInjection/DependencyInjectionExtension.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ResolvedFormTypeFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/Extension/DataCollector/Proxy/ResolvedTypeFactoryDataCollectorProxy.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ResolvedFormTypeFactory.php';

return $this->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService.php', true],
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService.php', true],
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['services', 'form.type.file', 'getForm_Type_FileService.php', true],
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService.php', true],
    'Webkul\\UVDesk\\AutomationBundle\\Form\\DefaultForm' => ['privates', 'Webkul\\UVDesk\\AutomationBundle\\Form\\DefaultForm', 'getDefaultFormService.php', true],
    'Webkul\\UVDesk\\CoreFrameworkBundle\\Form\\CreateTicket' => ['privates', 'Webkul\\UVDesk\\CoreFrameworkBundle\\Form\\CreateTicket', 'getCreateTicketService.php', true],
    'Webkul\\UVDesk\\CoreFrameworkBundle\\Form\\Mailbox' => ['privates', 'Webkul\\UVDesk\\CoreFrameworkBundle\\Form\\Mailbox', 'getMailboxService.php', true],
    'Webkul\\UVDesk\\CoreFrameworkBundle\\Form\\UserProfile' => ['privates', 'Webkul\\UVDesk\\CoreFrameworkBundle\\Form\\UserProfile', 'getUserProfileService.php', true],
    'Webkul\\UVDesk\\SupportCenterBundle\\Form\\AccountValidation' => ['privates', 'Webkul\\UVDesk\\SupportCenterBundle\\Form\\AccountValidation', 'getAccountValidationService.php', true],
    'Webkul\\UVDesk\\SupportCenterBundle\\Form\\ForgotPassword' => ['privates', 'Webkul\\UVDesk\\SupportCenterBundle\\Form\\ForgotPassword', 'getForgotPasswordService.php', true],
    'Webkul\\UVDesk\\SupportCenterBundle\\Form\\SolutionModal' => ['privates', 'Webkul\\UVDesk\\SupportCenterBundle\\Form\\SolutionModal', 'getSolutionModalService.php', true],
    'Webkul\\UVDesk\\SupportCenterBundle\\Form\\Ticket' => ['privates', 'Webkul\\UVDesk\\SupportCenterBundle\\Form\\Ticket', 'getTicket3Service.php', true],
], [
    'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
    'Webkul\\UVDesk\\AutomationBundle\\Form\\DefaultForm' => '?',
    'Webkul\\UVDesk\\CoreFrameworkBundle\\Form\\CreateTicket' => '?',
    'Webkul\\UVDesk\\CoreFrameworkBundle\\Form\\Mailbox' => '?',
    'Webkul\\UVDesk\\CoreFrameworkBundle\\Form\\UserProfile' => '?',
    'Webkul\\UVDesk\\SupportCenterBundle\\Form\\AccountValidation' => '?',
    'Webkul\\UVDesk\\SupportCenterBundle\\Form\\ForgotPassword' => '?',
    'Webkul\\UVDesk\\SupportCenterBundle\\Form\\SolutionModal' => '?',
    'Webkul\\UVDesk\\SupportCenterBundle\\Form\\Ticket' => '?',
]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.form.transformation_failure_handling'] ?? $this->load('getForm_TypeExtension_Form_TransformationFailureHandlingService.php'));
    yield 1 => ($this->privates['form.type_extension.form.http_foundation'] ?? $this->load('getForm_TypeExtension_Form_HttpFoundationService.php'));
    yield 2 => ($this->privates['form.type_extension.form.validator'] ?? $this->load('getForm_TypeExtension_Form_ValidatorService.php'));
    yield 3 => ($this->privates['form.type_extension.upload.validator'] ?? $this->load('getForm_TypeExtension_Upload_ValidatorService.php'));
    yield 4 => ($this->privates['form.type_extension.csrf'] ?? $this->load('getForm_TypeExtension_CsrfService.php'));
    yield 5 => ($this->privates['form.type_extension.form.data_collector'] ?? $this->load('getForm_TypeExtension_Form_DataCollectorService.php'));
}, 6), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.repeated.validator'] ?? ($this->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.submit.validator'] ?? ($this->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
}, 1)], new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_guesser.validator'] ?? $this->load('getForm_TypeGuesser_ValidatorService.php'));
    yield 1 => ($this->privates['form.type_guesser.doctrine'] ?? $this->load('getForm_TypeGuesser_DoctrineService.php'));
}, 2))], new \Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeFactoryDataCollectorProxy(new \Symfony\Component\Form\ResolvedFormTypeFactory(), ($this->privates['data_collector.form'] ?? $this->getDataCollector_FormService())));
