<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Webkul\UVDesk\ExtensionFrameworkBundle\Utils\ApplicationCollection' shared autowired service.

include_once $this->targetDirs[3].'/vendor/uvdesk/extension-framework/Utils/ApplicationCollection.php';

$this->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Utils\\ApplicationCollection'] = $instance = new \Webkul\UVDesk\ExtensionFrameworkBundle\Utils\ApplicationCollection($this, ($this->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Definition\\MappingResource'] ?? ($this->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Definition\\MappingResource'] = new \Webkul\UVDesk\ExtensionFrameworkBundle\Definition\MappingResource())), $this->load('getPackageCollectionService.php'));

$instance->organizeCollection();

return $instance;
