<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Webkul\UVDesk\CoreFrameworkBundle\FileSystem\UploadManagers\Localhost' shared autowired service.

include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/FileSystem/FileUploadServiceInterface.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/FileSystem/UploadManagers/Localhost.php';

return $this->services['Webkul\\UVDesk\\CoreFrameworkBundle\\FileSystem\\UploadManagers\\Localhost'] = new \Webkul\UVDesk\CoreFrameworkBundle\FileSystem\UploadManagers\Localhost($this, ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
