<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Webkul\UVDesk\ExtensionFrameworkBundle\Utils\PackageCollection' shared autowired service.

include_once $this->targetDirs[3].'/vendor/uvdesk/extension-framework/Utils/PackageCollection.php';

$instance = new \Webkul\UVDesk\ExtensionFrameworkBundle\Utils\PackageCollection($this, ($this->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Definition\\MappingResource'] ?? ($this->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Definition\\MappingResource'] = new \Webkul\UVDesk\ExtensionFrameworkBundle\Definition\MappingResource())));

$instance->organizeCollection();

return $instance;
