<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Webkul\UVDesk\CoreFrameworkBundle\Controller\PrivilegeXHR' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/Controller.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Controller/PrivilegeXHR.php';

return $this->services['Webkul\\UVDesk\\CoreFrameworkBundle\\Controller\\PrivilegeXHR'] = new \Webkul\UVDesk\CoreFrameworkBundle\Controller\PrivilegeXHR();
