<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'uvdesk.core.event_dispatcher' shared autowired service.

include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Framework/EventDispatcher.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/mailbox-component/EventListener/Swiftmailer.php';

$a = ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));

$this->services['uvdesk.core.event_dispatcher'] = $instance = new \Webkul\UVDesk\CoreFrameworkBundle\Framework\EventDispatcher($this, $a);

$instance->addEventListener(new \Webkul\UVDesk\MailboxBundle\EventListener\Swiftmailer($this, $a), [0 => ['event' => 'swiftmailer.configuration.updated', 'method' => 'onSwiftMailerConfigurationUpdated'], 1 => ['event' => 'swiftmailer.configuration.removed', 'method' => 'onSwiftMailerConfigurationRemoved']]);

return $instance;
