<?php

namespace Webkul\UVDesk\AutomationBundle\Repository;

/**
 * WorkflowEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowEventsRepository extends \Doctrine\ORM\EntityRepository
{
}
