<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ao9tG3f' shared service.

return $this->privates['.service_locator.Ao9tG3f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'quickActionButtonCollection' => ['privates', 'Webkul\\UVDesk\\CoreFrameworkBundle\\Tickets\\QuickActionButtonCollection', 'getQuickActionButtonCollectionService', false],
], [
    'quickActionButtonCollection' => 'Webkul\\UVDesk\\CoreFrameworkBundle\\Tickets\\QuickActionButtonCollection',
]);
