<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Webkul\UVDesk\CoreFrameworkBundle\EventListener\Doctrine\Lifecycle' shared autowired service.

include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/EventListener/Doctrine/Lifecycle.php';

return $this->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\EventListener\\Doctrine\\Lifecycle'] = new \Webkul\UVDesk\CoreFrameworkBundle\EventListener\Doctrine\Lifecycle($this);
