<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.X8tWLT6' shared service.

return $this->privates['.service_locator.X8tWLT6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BaseController::base' => ['privates', '.service_locator.TXBGN0c', 'get_ServiceLocator_TXBGN0cService.php', true],
    'App\\Controller\\ConfigureHelpdesk::migrateDatabaseSchemaXHR' => ['privates', '.service_locator.l9NCai0', 'get_ServiceLocator_L9NCai0Service.php', true],
    'App\\Controller\\ConfigureHelpdesk::populateDatabaseEntitiesXHR' => ['privates', '.service_locator.l9NCai0', 'get_ServiceLocator_L9NCai0Service.php', true],
    'App\\Controller\\ConfigureHelpdesk::updateConfigurationsXHR' => ['privates', '.service_locator.l9NCai0', 'get_ServiceLocator_L9NCai0Service.php', true],
    'Webkul\\UVDesk\\CoreFrameworkBundle\\Controller\\Ticket::loadTicket' => ['privates', '.service_locator.Ao9tG3f', 'get_ServiceLocator_Ao9tG3fService.php', true],
    'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Controller\\Application::apiEndpointXHR' => ['privates', '.service_locator.aC5KO5E', 'get_ServiceLocator_AC5KO5EService.php', true],
    'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Controller\\Application::dashboard' => ['privates', '.service_locator.t1GQV3c', 'get_ServiceLocator_T1GQV3cService.php', true],
    'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Controller\\Dashboard::applicationsXHR' => ['privates', '.service_locator.Z_keyIL', 'get_ServiceLocator_ZKeyILService.php', true],
    'App\\Controller\\BaseController:base' => ['privates', '.service_locator.TXBGN0c', 'get_ServiceLocator_TXBGN0cService.php', true],
    'App\\Controller\\ConfigureHelpdesk:migrateDatabaseSchemaXHR' => ['privates', '.service_locator.l9NCai0', 'get_ServiceLocator_L9NCai0Service.php', true],
    'App\\Controller\\ConfigureHelpdesk:populateDatabaseEntitiesXHR' => ['privates', '.service_locator.l9NCai0', 'get_ServiceLocator_L9NCai0Service.php', true],
    'App\\Controller\\ConfigureHelpdesk:updateConfigurationsXHR' => ['privates', '.service_locator.l9NCai0', 'get_ServiceLocator_L9NCai0Service.php', true],
    'Webkul\\UVDesk\\CoreFrameworkBundle\\Controller\\Ticket:loadTicket' => ['privates', '.service_locator.Ao9tG3f', 'get_ServiceLocator_Ao9tG3fService.php', true],
    'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Controller\\Application:apiEndpointXHR' => ['privates', '.service_locator.aC5KO5E', 'get_ServiceLocator_AC5KO5EService.php', true],
    'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Controller\\Application:dashboard' => ['privates', '.service_locator.t1GQV3c', 'get_ServiceLocator_T1GQV3cService.php', true],
    'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Controller\\Dashboard:applicationsXHR' => ['privates', '.service_locator.Z_keyIL', 'get_ServiceLocator_ZKeyILService.php', true],
], [
    'App\\Controller\\BaseController::base' => '?',
    'App\\Controller\\ConfigureHelpdesk::migrateDatabaseSchemaXHR' => '?',
    'App\\Controller\\ConfigureHelpdesk::populateDatabaseEntitiesXHR' => '?',
    'App\\Controller\\ConfigureHelpdesk::updateConfigurationsXHR' => '?',
    'Webkul\\UVDesk\\CoreFrameworkBundle\\Controller\\Ticket::loadTicket' => '?',
    'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Controller\\Application::apiEndpointXHR' => '?',
    'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Controller\\Application::dashboard' => '?',
    'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Controller\\Dashboard::applicationsXHR' => '?',
    'App\\Controller\\BaseController:base' => '?',
    'App\\Controller\\ConfigureHelpdesk:migrateDatabaseSchemaXHR' => '?',
    'App\\Controller\\ConfigureHelpdesk:populateDatabaseEntitiesXHR' => '?',
    'App\\Controller\\ConfigureHelpdesk:updateConfigurationsXHR' => '?',
    'Webkul\\UVDesk\\CoreFrameworkBundle\\Controller\\Ticket:loadTicket' => '?',
    'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Controller\\Application:apiEndpointXHR' => '?',
    'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Controller\\Application:dashboard' => '?',
    'Webkul\\UVDesk\\ExtensionFrameworkBundle\\Controller\\Dashboard:applicationsXHR' => '?',
]);
