<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Webkul\UVDesk\SupportCenterBundle\Form\AccountValidation' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/support-center-bundle/Form/AccountValidation.php';

return $this->privates['Webkul\\UVDesk\\SupportCenterBundle\\Form\\AccountValidation'] = new \Webkul\UVDesk\SupportCenterBundle\Form\AccountValidation();
