<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.Webkul\UVDesk\ExtensionFrameworkBundle\Console\BuildExtensions' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/extension-framework/Console/BuildExtensions.php';

return $this->services['console.command.public_alias.Webkul\\UVDesk\\ExtensionFrameworkBundle\\Console\\BuildExtensions'] = new \Webkul\UVDesk\ExtensionFrameworkBundle\Console\BuildExtensions($this);
