<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Webkul\UVDesk\ExtensionFrameworkBundle\EventListener\Console' shared autowired service.

include_once $this->targetDirs[3].'/vendor/uvdesk/extension-framework/EventListener/Console.php';

return $this->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\EventListener\\Console'] = new \Webkul\UVDesk\ExtensionFrameworkBundle\EventListener\Console($this, ($this->services['kernel'] ?? $this->get('kernel', 1)), ($this->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Definition\\MappingResource'] ?? ($this->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Definition\\MappingResource'] = new \Webkul\UVDesk\ExtensionFrameworkBundle\Definition\MappingResource())));
