<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.dump_listener' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/EventListener/DumpListener.php';

return $this->privates['debug.dump_listener'] = new \Symfony\Component\HttpKernel\EventListener\DumpListener(($this->services['var_dumper.cloner'] ?? $this->getVarDumper_ClonerService()), ($this->privates['var_dumper.cli_dumper'] ?? $this->load('getVarDumper_CliDumperService.php')), ($this->privates['var_dumper.server_connection'] ?? $this->getVarDumper_ServerConnectionService()));
