<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.App\Console\EnvironmentVariables' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Console/EnvironmentVariables.php';

return $this->services['console.command.public_alias.App\\Console\\EnvironmentVariables'] = new \App\Console\EnvironmentVariables($this);
