<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.Webkul\UVDesk\MailboxBundle\Console\RefreshMailboxCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/mailbox-component/Console/RefreshMailboxCommand.php';

return $this->services['console.command.public_alias.Webkul\\UVDesk\\MailboxBundle\\Console\\RefreshMailboxCommand'] = new \Webkul\UVDesk\MailboxBundle\Console\RefreshMailboxCommand($this, ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
