<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'routing.loader' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/config/Loader/LoaderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/config/Loader/Loader.php';
include_once $this->targetDirs[3].'/vendor/symfony/config/Loader/DelegatingLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Routing/DelegatingLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/config/Loader/LoaderResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/config/Loader/LoaderResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/config/Loader/FileLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/XmlFileLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/config/FileLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/config/FileLocator.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Config/FileLocator.php';
include_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/YamlFileLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/PhpFileLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/GlobFileLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/DirectoryLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/ObjectRouteLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/DependencyInjection/ServiceRouterLoader.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Definition/RouterInterface.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Definition/RouteLoader.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Definition/RoutingResourceInterface.php';
include_once $this->targetDirs[3].'/src/Routing/RoutingResource.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Routing/RoutingResource.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/automation-bundle/Routing/RoutingResource.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/extension-framework/Routing/RoutingResource.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/mailbox-component/Routing/RoutingResource.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/support-center-bundle/Routing/RoutingResource.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/extension-framework/Definition/RouteLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/AnnotationClassLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Routing/AnnotatedRouteControllerLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/AnnotationFileLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/AnnotationDirectoryLoader.php';

$a = new \Symfony\Component\Config\Loader\LoaderResolver();

$b = new \Symfony\Component\HttpKernel\Config\FileLocator(($this->services['kernel'] ?? $this->get('kernel', 1)), ($this->targetDirs[3].'/src/Resources'), [0 => ($this->targetDirs[3].'/src')]);
$c = new \Webkul\UVDesk\CoreFrameworkBundle\Definition\RouteLoader($this);
$c->addRoutingResource(new \App\Routing\RoutingResource(), [0 => []]);
$c->addRoutingResource(new \Webkul\UVDesk\CoreFrameworkBundle\Routing\RoutingResource(), [0 => []]);
$c->addRoutingResource(new \Webkul\UVDesk\AutomationBundle\Routing\RoutingResource(), [0 => []]);
$c->addRoutingResource(new \Webkul\UVDesk\ExtensionFrameworkBundle\Routing\RoutingResource(), [0 => []]);
$c->addRoutingResource(new \Webkul\UVDesk\MailboxBundle\Routing\RoutingResource(), [0 => []]);
$c->addRoutingResource(new \Webkul\UVDesk\SupportCenterBundle\Routing\RoutingResource(), [0 => []]);
$d = new \Symfony\Bundle\FrameworkBundle\Routing\AnnotatedRouteControllerLoader(($this->privates['annotations.cached_reader'] ?? $this->getAnnotations_CachedReaderService()));

$a->addLoader(new \Symfony\Component\Routing\Loader\XmlFileLoader($b));
$a->addLoader(new \Symfony\Component\Routing\Loader\YamlFileLoader($b));
$a->addLoader(new \Symfony\Component\Routing\Loader\PhpFileLoader($b));
$a->addLoader(new \Symfony\Component\Routing\Loader\GlobFileLoader($b));
$a->addLoader(new \Symfony\Component\Routing\Loader\DirectoryLoader($b));
$a->addLoader(new \Symfony\Component\Routing\Loader\DependencyInjection\ServiceRouterLoader($this));
$a->addLoader($c);
$a->addLoader(new \Webkul\UVDesk\ExtensionFrameworkBundle\Definition\RouteLoader($this));
$a->addLoader($d);
$a->addLoader(new \Symfony\Component\Routing\Loader\AnnotationDirectoryLoader($b, $d));
$a->addLoader(new \Symfony\Component\Routing\Loader\AnnotationFileLoader($b, $d));

return $this->services['routing.loader'] = new \Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader(($this->privates['controller_name_converter'] ?? ($this->privates['controller_name_converter'] = new \Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser(($this->services['kernel'] ?? $this->get('kernel', 1))))), $a, ['utf8' => true]);
