<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.security.voter.Webkul\UVDesk\CoreFrameworkBundle\Security\TicketVoter' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-core/Authorization/Voter/Voter.php';
include_once $this->targetDirs[3].'/vendor/uvdesk/core-framework/Security/TicketVoter.php';

return $this->privates['debug.security.voter.Webkul\\UVDesk\\CoreFrameworkBundle\\Security\\TicketVoter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(new \Webkul\UVDesk\CoreFrameworkBundle\Security\TicketVoter($this, ($this->privates['debug.security.access.decision_manager'] ?? $this->getDebug_Security_Access_DecisionManagerService())), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
