<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'web_server.command.server_log' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/web-server-bundle/Command/ServerLogCommand.php';

$this->privates['web_server.command.server_log'] = $instance = new \Symfony\Bundle\WebServerBundle\Command\ServerLogCommand();

$instance->setName('server:log');

return $instance;
