<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL29bxuT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL29bxuT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL29bxuT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL29bxuT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerL29bxuT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'L29bxuT',
    'container.build_id' => '7a54cd82',
    'container.build_time' => 1569480306,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL29bxuT');
