<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWiH9VWx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWiH9VWx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWiH9VWx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWiH9VWx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWiH9VWx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WiH9VWx',
    'container.build_id' => 'baa08446',
    'container.build_time' => 1569232318,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWiH9VWx');
