<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container706X6BS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container706X6BS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container706X6BS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container706X6BS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container706X6BS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '706X6BS',
    'container.build_id' => '79325511',
    'container.build_time' => 1569411080,
], __DIR__.\DIRECTORY_SEPARATOR.'Container706X6BS');
